server:
  port: 9001

spring:
  application:
    name: thingsForDesignPattern

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
#    host: 192.168.255.130
    host: 192.168.64.128
    port: 6379

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.255.130:3306/thing_for_design_pattern?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://192.168.64.128:3306/thing_for_design_pattern?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:/mapperxml/*.xml
    type-aliases-package: com.uiys.thingsfordesignpattern.mapper


