server:
  port: 9001

spring:
  application:
    name: thingsForDesignPattern

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
    host: 192.168.255.130
    port: 6379

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.255.130:3306/thing_for_design_pattern?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #    url: jdbc:mysql://192.168.64.128:3306/thingImportant?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:/mapperxml/*.xml
    type-aliases-package: com.uiys.thingsfordesignpattern.mapper




## 应用名称
#spring.application.name=thingsforDesignPattern
#  # 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  # 数据源名称
#spring.datasource.name=defaultDataSource
#  # 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
#  # 数据库用户名&密码：
#spring.datasource.username=***
#spring.datasource.password=***
#  # 应用服务 WEB 访问端口
#server.port=8080